import { createService, createAuthMethod } from '../../domain'
import type { Service } from '../../domain'

export function getServiceCatalog(): readonly Service[] {
  return [
    createService({
      id: 'customers',
      name: 'Customers',
      description: 'Customer identity, KYC verification, risk scoring, and audit trails.',
      port: 5501,
      auth: createAuthMethod('api-key'),
      tools: [
        { name: 'search_customers', description: 'Search by name, email, ID number' },
        { name: 'get_customer', description: 'Full customer profile' },
        { name: 'list_customers', description: 'List with status/KYC filters' },
        { name: 'create_customer', description: 'Register new customer' },
        { name: 'update_customer', description: 'Update contact details' },
        { name: 'get_kyc_status', description: 'KYC verification status' },
        { name: 'verify_customer', description: 'Mark as KYC verified' },
        { name: 'suspend_customer', description: 'Suspend account' },
        { name: 'get_audit_log', description: 'View audit trail' },
        { name: 'get_risk_assessment', description: 'Risk score and flags' },
      ],
    }),
    createService({
      id: 'wallets',
      name: 'Wallets',
      description: 'Accounts, balances, transactions, P2P transfers, and scheduled payments.',
      port: 5502,
      auth: createAuthMethod('jwt'),
      tools: [
        { name: 'get_balance', description: 'Current and available balance' },
        { name: 'list_wallets', description: 'All wallets for customer' },
        { name: 'list_transactions', description: 'Filtered transaction history' },
        { name: 'get_transaction', description: 'Transaction by ID or reference' },
        { name: 'transfer', description: 'P2P or own-account transfer' },
        { name: 'pay_external', description: 'EFT to external bank' },
        { name: 'get_spending_summary', description: 'Category breakdown' },
        { name: 'list_scheduled_payments', description: 'Recurring payments' },
        { name: 'freeze_wallet', description: 'Freeze for security' },
        { name: 'get_statement', description: 'Mini-statement with balances' },
      ],
    }),
    createService({
      id: 'loans',
      name: 'Loans',
      description: 'Loan management, payments, amortization, and applications.',
      port: 5503,
      auth: createAuthMethod('oauth2'),
      tools: [
        { name: 'list_loans', description: 'All loans for customer' },
        { name: 'get_loan_details', description: 'Full loan information' },
        { name: 'get_loan_balance', description: 'Outstanding balance' },
        { name: 'get_next_payment', description: 'Next payment due' },
        { name: 'get_payment_schedule', description: 'Upcoming installments' },
        { name: 'list_payments', description: 'Payment history' },
        { name: 'make_payment', description: 'Make a loan payment' },
        { name: 'get_loan_summary', description: 'Total commitments overview' },
        { name: 'apply_for_loan', description: 'Submit application' },
        { name: 'check_application_status', description: 'Application tracking' },
        { name: 'calculate_loan', description: 'Monthly payment calculator' },
        { name: 'get_amortization', description: 'Amortization table' },
      ],
    }),
    createService({
      id: 'insurance',
      name: 'Insurance',
      description: 'Policies, premiums, claims, and beneficiary management.',
      port: 5504,
      auth: createAuthMethod('hmac'),
      tools: [
        { name: 'list_policies', description: 'All insurance policies' },
        { name: 'get_policy_details', description: 'Policy with beneficiaries/claims' },
        { name: 'get_premium_info', description: 'Premium and frequency' },
        { name: 'get_next_premium', description: 'Next premium due' },
        { name: 'list_premium_payments', description: 'Payment history' },
        { name: 'pay_premium', description: 'Make premium payment' },
        { name: 'submit_claim', description: 'File an insurance claim' },
        { name: 'check_claim_status', description: 'Claim status tracking' },
        { name: 'list_claims', description: 'All claims with filters' },
        { name: 'get_cover_summary', description: 'Total cover overview' },
        { name: 'list_beneficiaries', description: 'Policy beneficiaries' },
        { name: 'get_insurance_overview', description: 'Complete insurance snapshot' },
      ],
    }),
    createService({
      id: 'platform',
      name: 'Platform',
      description: 'Unified gateway with cross-service dashboards, activity feeds, and admin tools.',
      port: 5500,
      auth: createAuthMethod('session'),
      tools: [
        { name: 'get_dashboard', description: 'Main banking dashboard' },
        { name: 'get_activity_feed', description: 'Cross-service activity' },
        { name: 'get_notifications', description: 'Alerts and notifications' },
        { name: 'mark_notification_read', description: 'Dismiss notifications' },
        { name: 'get_financial_overview', description: 'Total assets/liabilities' },
        { name: 'search_activity', description: 'Search across services' },
        { name: 'get_upcoming_payments', description: 'All upcoming payments' },
        { name: 'get_monthly_summary', description: 'Income vs expenses' },
        { name: 'view_customer_360', description: 'Admin: full customer view' },
        { name: 'list_all_customers', description: 'Admin: all customers' },
        { name: 'track_cross_service_transaction', description: 'Trace a reference across services' },
      ],
    }),
  ]
}
